In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.FloatTensor(3, 4, 5).random_()
a

tensor([[[ 6410222.,  9415466.,   823169.,  8177327.,  2825035.],
         [ 7122669., 11833693.,  5933717.,  8888619.,  6089285.],
         [ 6578414., 11196324.,  1387024., 14572449., 10538346.],
         [ 3936281.,   631734., 12735334.,  2135243., 14257941.]],

        [[ 3133021., 10327150., 10580523.,  3829548.,  8941168.],
         [12180172.,  2181936.,  5662690.,  2601455., 13206212.],
         [ 5332098.,  5980923.,  7710328.,   595574.,  3107847.],
         [ 4600730., 10318935., 10599844.,  9340399., 12072730.]],

        [[ 6542997.,  3957642.,  4000320.,  1077713.,  6985279.],
         [ 2216262.,  3468797., 13847291.,  9424241.,  5037894.],
         [ 5765376.,  1724972.,  9789546.,  7725025., 14171739.],
         [10619993.,   820824., 10450477.,  5938336.,  2181923.]]])

In [4]:
# 2. Выведите его форму (shape)

In [5]:
a.shape # или a.size()

torch.Size([3, 4, 5])

In [6]:
# 3. Приведите его к форме 6х10

In [7]:
a = a.reshape(6, 10)
a

tensor([[ 6410222.,  9415466.,   823169.,  8177327.,  2825035.,  7122669.,
         11833693.,  5933717.,  8888619.,  6089285.],
        [ 6578414., 11196324.,  1387024., 14572449., 10538346.,  3936281.,
           631734., 12735334.,  2135243., 14257941.],
        [ 3133021., 10327150., 10580523.,  3829548.,  8941168., 12180172.,
          2181936.,  5662690.,  2601455., 13206212.],
        [ 5332098.,  5980923.,  7710328.,   595574.,  3107847.,  4600730.,
         10318935., 10599844.,  9340399., 12072730.],
        [ 6542997.,  3957642.,  4000320.,  1077713.,  6985279.,  2216262.,
          3468797., 13847291.,  9424241.,  5037894.],
        [ 5765376.,  1724972.,  9789546.,  7725025., 14171739., 10619993.,
           820824., 10450477.,  5938336.,  2181923.]])

In [8]:
a.size() # или a.shape

torch.Size([6, 10])

In [9]:
# 4. Создайте случайный IntTensor размера 10

In [10]:
b = torch.IntTensor(10).random_()
b

tensor([ 319446971,  947866683, 1736617873,  606159545, 1066106703, 1874485862,
        2051548861, 1687611366, 1469263738, 1814670758], dtype=torch.int32)

In [11]:
b.shape # или b.size()

torch.Size([10])

In [12]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [13]:
a_new = a.mul_(b)
a_new

tensor([[2.0477e+15, 8.9246e+15, 1.4295e+15, 4.9568e+15, 3.0118e+15, 1.3351e+16,
         2.4277e+16, 1.0014e+16, 1.3060e+16, 1.1050e+16],
        [2.1015e+15, 1.0613e+16, 2.4087e+15, 8.8332e+15, 1.1235e+16, 7.3785e+15,
         1.2960e+15, 2.1492e+16, 3.1372e+15, 2.5873e+16],
        [1.0008e+15, 9.7888e+15, 1.8374e+16, 2.3213e+15, 9.5322e+15, 2.2832e+16,
         4.4763e+15, 9.5564e+15, 3.8222e+15, 2.3965e+16],
        [1.7033e+15, 5.6691e+15, 1.3390e+16, 3.6101e+14, 3.3133e+15, 8.6240e+15,
         2.1170e+16, 1.7888e+16, 1.3724e+16, 2.1908e+16],
        [2.0901e+15, 3.7513e+15, 6.9470e+15, 6.5327e+14, 7.4471e+15, 4.1544e+15,
         7.1164e+15, 2.3369e+16, 1.3847e+16, 9.1421e+15],
        [1.8417e+15, 1.6350e+15, 1.7001e+16, 4.6826e+15, 1.5109e+16, 1.9907e+16,
         1.6840e+15, 1.7636e+16, 8.7250e+15, 3.9595e+15]])

In [14]:
a_new.shape # или a_new.size()

torch.Size([6, 10])

In [15]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [16]:
a_new_t = a_new.T
a_new_t 

tensor([[2.0477e+15, 2.1015e+15, 1.0008e+15, 1.7033e+15, 2.0901e+15, 1.8417e+15],
        [8.9246e+15, 1.0613e+16, 9.7888e+15, 5.6691e+15, 3.7513e+15, 1.6350e+15],
        [1.4295e+15, 2.4087e+15, 1.8374e+16, 1.3390e+16, 6.9470e+15, 1.7001e+16],
        [4.9568e+15, 8.8332e+15, 2.3213e+15, 3.6101e+14, 6.5327e+14, 4.6826e+15],
        [3.0118e+15, 1.1235e+16, 9.5322e+15, 3.3133e+15, 7.4471e+15, 1.5109e+16],
        [1.3351e+16, 7.3785e+15, 2.2832e+16, 8.6240e+15, 4.1544e+15, 1.9907e+16],
        [2.4277e+16, 1.2960e+15, 4.4763e+15, 2.1170e+16, 7.1164e+15, 1.6840e+15],
        [1.0014e+16, 2.1492e+16, 9.5564e+15, 1.7888e+16, 2.3369e+16, 1.7636e+16],
        [1.3060e+16, 3.1372e+15, 3.8222e+15, 1.3724e+16, 1.3847e+16, 8.7250e+15],
        [1.1050e+16, 2.5873e+16, 2.3965e+16, 2.1908e+16, 9.1421e+15, 3.9595e+15]])

In [17]:
a_new_t.shape # или a_new_t.size()

torch.Size([10, 6])

In [18]:
a_66 = a_new.mm(a_new_t)
a_66

tensor([[1.2801e+33, 8.5215e+32, 9.7983e+32, 1.3145e+33, 8.1746e+32, 7.5235e+32],
        [8.5215e+32, 1.5244e+33, 1.2895e+33, 1.2218e+33, 9.7248e+32, 9.3121e+32],
        [9.7983e+32, 1.2895e+33, 1.7523e+33, 1.3757e+33, 8.6101e+32, 1.2439e+33],
        [1.3145e+33, 1.2218e+33, 1.3757e+33, 1.7363e+33, 1.1376e+33, 1.0211e+33],
        [8.1746e+32, 9.7248e+32, 8.6101e+32, 1.1376e+33, 1.0119e+33, 9.0750e+32],
        [7.5235e+32, 9.3121e+32, 1.2439e+33, 1.0211e+33, 9.0750e+32, 1.3473e+33]])

In [19]:
a_66.shape # или a_66.size()

torch.Size([6, 6])

In [20]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [21]:
def backward(incoming_gradients):
    self.Tensor.grad = incoming_gradients

    for inp in self.inputs:
        if inp.grad_fn is not None:
            new_incoming_gradients = incoming_gradient * local_grad(self.Tensor, inp)
            inp.grad_fn.backward(new_incoming_gradients)
        else:
            pass

In [22]:
x = torch.tensor(1., requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2., requires_grad=True)

In [23]:
y = x ** 3 + z - 75 * t
y

tensor(-148.5000, grad_fn=<SubBackward0>)

In [24]:
y.backward()

In [25]:
# 8. Создайте единичный тензор размера 5x6

In [26]:
a = torch.ones(5, 6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [27]:
a.shape # или a.size()

torch.Size([5, 6])

In [28]:
# 9. Переведите его в формат numpy

In [29]:
a_n = a.numpy()
a_n

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [30]:
type(a_n)

numpy.ndarray